version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain marcal --domain-owner 441479161631 --query authorizationToken --output text`
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo building...
      - ng build
  post_build:
    commands:
      - echo testing...
      - ng test
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-pet-store
 
