version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs and aws cli ...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - pip3 install awscli --upgrade --user
  pre_build:
    commands:
      - echo installing dependencies...
      - aws codeartifact login --tool npm --domain marcal --domain-owner 441479161631 --repository DAP-rep 
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo building...
      - ng build
  post_build:
    commands:
      - echo testing...
      - ng test
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-pet-store
